version: "3"
services:
  manifoldcf-db:
    image: postgres:9.6.14
    environment:
      # By default, POSTGRES_DB equals POSTGRES_USER. If you override POSTGRES_DB here then you must also override in manifoldcf-web.
      POSTGRES_USER: manifoldcf
      POSTGRES_PASSWORD: "man1f0ldcf!"
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432
  manifoldcf-web:
    depends_on:
      - manifoldcf-db
    environment:
      POSTGRES_HOSTNAME: manifoldcf-db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: "man1f0ldcf!"
      POSTGRES_SSL: "false"
    image: perficientdevops/manifoldcf:2.11
    ports:
      - 8345:8345
    volumes:
      - /var/manifoldcf
